name: scipy2020
channels:
  - bokeh
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python
  - pip
  - jupyterlab
  - requests
  # dask
  - dask
  - distributed
  # numerical
  - numpy
  - pandas < 1.0
  - pyarrow
  - fastparquet
  - pytest
  # visualization 
  - matplotlib
  - bokeh
  - holoviews
  - geoviews
  - datashader
  - hvplot
  # geopackages
  - geopandas
  - datashader
  - python-geohash
  - kartothek
  - shapely
  - spatialpandas
  - cartopy
  # other
  - setuptools
  - python-snappy
  - nodejs
  - pip:
    - polygon-geohasher
  
  #  jupyter labextension install @pyviz/jupyterlab_pyviz
